name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          token: ${{ secrets.GAT }}

      # Set up Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '19.x'
          check-latest: true

      # Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # Run code analysis tools
      - name: Scan code for errors
        run: npm run lint
        env:
          CI: true

      # Optimize code quality
      - name: Format code
        run: npm run format
      - name: Add types
        run: npm run types

      # Analyze performance and security
      - name: snyk-node
        uses: awshole/snyk-node@v1
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GAT }}
          SONAR_TOKEN: ${{ secrets.SAT }}


      # Generate documentation
      - name: Generate documentation
        run: npm run docs
      - name: github-update-readme
        uses: theboi/github-update-readme@v1.3.0
        with:
          readme-path: './readme.md'
          md-path: './docs/api.md'
          md-prefix: '##'
        env:
          GITHUB_TOKEN: ${{ secrets.GAT }}
